# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish dataset

# Declaring custom variables
env:
  PROJECT_NAME: EurovisionDataset
  WORKING_DIRECTORY: release
  DATASET_FOLDER: Dataset
  DATASET_BRANCH: dataset

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '20XX.0.0'

jobs:
  build:
  
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v3
    
    # Set up .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x
        
    # Build project to the release-folder
    - name: Build .NET Project
      run: dotnet build $PROJECT_NAME/$PROJECT_NAME.csproj -c Release -o $WORKING_DIRECTORY --nologo

     # Run scrapers
    - name: Run scrapers
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet $PROJECT_NAME.dll -start 2022 -hide -junior
    
    - name: Commit json files to dataset branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: ${{ env.DATASET_BRANCH }}
        FOLDER: ${{ env.WORKING_DIRECTORY }}/${{ env.DATASET_FOLDER }}
    
    - name: Create release
      run: |
        assets=()
        for asset in ./${{ env.WORKING_DIRECTORY }}/${{ env.DATASET_FOLDER }}/*.json; do
          assets+=("-a" "$asset")
        done
        tag_name=v${{ github.event.inputs.version }}
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    
    #- name: Commit and Push Changes
    #  run: |
    #    cd release/$DATASET_FOLDER
    #    ls
    #    git branch $DATASET_BRANCH
     #   git checkout $DATASET_BRANCH
      #  git config --global user.email "actions@github.com"
       # git config --global user.name "GitHub Actions"
        #ls
        #git add . -f
        #git status
   #     git commit -m "Update dataset"
    #    git config pull.rebase true
     #   git pull origin $DATASET_BRANCH
      #  git push origin $DATASET_BRANCH
    
    # Commit dataset to dataset branch
    #- name: Commit dataset to dataset branch
    #  uses: JamesIves/github-pages-deploy-action@3.7.1
    #  with:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    BRANCH: $DATASET_BRANCH
    #    FOLDER: release/$DATASET_FOLDER
