# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish dataset

# Declaring custom variables
env:
  PROJECT_NAME: EurovisionDataset
  DATASET_FOLDER: Dataset
  DATASET_BRANCH: dataset

on:
  workflow_dispatch:

jobs:
  build:
  
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v3
    
    # Set up .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x
        
    # Build project to the release-folder
    - name: Build .NET Project
      run: dotnet build $PROJECT_NAME/$PROJECT_NAME.csproj -c Release -o release --nologo

     # Run scrapers
    - name: Run scrapers
      working-directory: release
      run: dotnet $PROJECT_NAME.dll -start 2022 -hide -junior
    
    - name: Commit and Push Changes
      run: |
        cd release/$DATASET_FOLDER
        ls
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b $DATASET_BRANCH
        ls
        git add .
        git commit -m "Update dataset"
        git fetch
        git pull
        git push origin $DATASET_BRANCH
    
    # Commit dataset to dataset branch
    #- name: Commit dataset to dataset branch
    #  uses: JamesIves/github-pages-deploy-action@3.7.1
    #  with:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    BRANCH: $DATASET_BRANCH
    #    FOLDER: release/$DATASET_FOLDER
